# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: "ceo@tharhonda.com", password: "12345678", password_confirmation: "12345678")

Month.create(name: "Jan")
Month.create(name: "Feb")
Month.create(name: "Mar")
Month.create(name: "Apr")
Month.create(name: "May")
Month.create(name: "Jun")
Month.create(name: "Jul")
Month.create(name: "Aug")
Month.create(name: "Sep")
Month.create(name: "Oct")
Month.create(name: "Nov")
Month.create(name: "Dec")

Year.create(name: "2009-10")
Year.create(name: "2010-11")
Year.create(name: "2011-12")
Year.create(name: "2012-13")
Year.create(name: "2013-14")
Year.create(name: "2014-15")
Year.create(name: "2015-16")

Network.create(name: "Hindustan Motors")
Network.create(name: "Khokar Automobiles")
Network.create(name: "Hitesh Motors")
Network.create(name: "Laxmi Motors")
Network.create(name: "Jai Ambay Motors")
Network.create(name: "Matoliya Motors")
Network.create(name: "Ganpati Motors")
Network.create(name: "Bharat Motors")
Network.create(name: "Shri Shyam Automobiles")
Network.create(name: "Radha Swami Automobiles")
Network.create(name: "Shahpura Motors")
Network.create(name: "Vebhav Laxmi Motors")
Network.create(name: "Shri Ganesh Automobiles")
Network.create(name: "Shri Sai Motors")
Network.create(name: "Kamla Motors")
Network.create(name: "Giriraj Motors")

Head.create(name: "Narendra")
Head.create(name: "Kamlesh Kumawat")
Head.create(name: "Anil")
Head.create(name: "Vikash Sharma")
Head.create(name: "Vikash Kumawat")
Head.create(name: "Pawan")
Head.create(name: "Mithlesh")
Head.create(name: "Manoj")
Head.create(name: "Nitesh")
Head.create(name: "Ramesh")
Head.create(name: "Subham")
Head.create(name: "Shankar")

Model.create(name: "Activa i")
Model.create(name: "Activa")
Model.create(name: "Activa 125")
Model.create(name: "Dio")
Model.create(name: "Aviator")
Model.create(name: "Twister")
Model.create(name: "Shine")
Model.create(name: "Stunner")
Model.create(name: "Unicorn")
Model.create(name: "Trigger")
Model.create(name: "CBR 150")
Model.create(name: "CBR 250")
Model.create(name: "CD 110")
Model.create(name: "Dream Neo")
Model.create(name: "Dream Yuga")

#Apr 2015 Network
Nretail.create(network_id:1, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:2, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:1, model_id:3, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:6, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:1, model_id:7, month_id:4, year_id:7, number:4, target:1)
Nretail.create(network_id:1, model_id:8, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:1, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:10, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:1, model_id:13, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:1, model_id:14, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:1, model_id:15, month_id:4, year_id:7, number:0, target:3)
Nretail.create(network_id:2, model_id:1, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:2, model_id:2, month_id:4, year_id:7, number:5, target:6)
Nretail.create(network_id:2, model_id:3, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:2, model_id:4, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:2, model_id:5, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:2, model_id:6, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:2, model_id:7, month_id:4, year_id:7, number:10, target:15)
Nretail.create(network_id:2, model_id:8, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:2, model_id:9, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:2, model_id:10, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:2, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:2, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:2, model_id:13, month_id:4, year_id:7, number:1, target:9)
Nretail.create(network_id:2, model_id:14, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:2, model_id:15, month_id:4, year_id:7, number:2, target:8)
Nretail.create(network_id:3, model_id:1, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:3, model_id:2, month_id:4, year_id:7, number:13, target:8)
Nretail.create(network_id:3, model_id:3, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:3, model_id:4, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:3, model_id:5, month_id:4, year_id:7, number:0, target:3)
Nretail.create(network_id:3, model_id:6, month_id:4, year_id:7, number:2, target:2)
Nretail.create(network_id:3, model_id:7, month_id:4, year_id:7, number:18, target:19)
Nretail.create(network_id:3, model_id:8, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:3, model_id:9, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:3, model_id:10, month_id:4, year_id:7, number:1, target:4)
Nretail.create(network_id:3, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:3, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:3, model_id:13, month_id:4, year_id:7, number:4, target:13)
Nretail.create(network_id:3, model_id:14, month_id:4, year_id:7, number:0, target:3)
Nretail.create(network_id:3, model_id:15, month_id:4, year_id:7, number:21, target:12)
Nretail.create(network_id:4, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:4, model_id:2, month_id:4, year_id:7, number:4, target:3)
Nretail.create(network_id:4, model_id:3, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:4, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:4, model_id:5, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:4, model_id:6, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:4, model_id:7, month_id:4, year_id:7, number:7, target:6)
Nretail.create(network_id:4, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:4, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:4, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:4, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:4, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:4, model_id:13, month_id:4, year_id:7, number:4, target:10)
Nretail.create(network_id:4, model_id:14, month_id:4, year_id:7, number:1, target:4)
Nretail.create(network_id:4, model_id:15, month_id:4, year_id:7, number:7, target:8)
Nretail.create(network_id:5, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:2, month_id:4, year_id:7, number:5, target:3)
Nretail.create(network_id:5, model_id:3, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:5, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:6, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:5, model_id:7, month_id:4, year_id:7, number:3, target:5)
Nretail.create(network_id:5, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:10, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:5, model_id:13, month_id:4, year_id:7, number:10, target:6)
Nretail.create(network_id:5, model_id:14, month_id:4, year_id:7, number:0, target:3)
Nretail.create(network_id:5, model_id:15, month_id:4, year_id:7, number:4, target:4)
Nretail.create(network_id:6, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:2, month_id:4, year_id:7, number:1, target:2)
Nretail.create(network_id:6, model_id:3, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:6, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:6, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:7, month_id:4, year_id:7, number:2, target:3)
Nretail.create(network_id:6, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:10, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:6, model_id:13, month_id:4, year_id:7, number:2, target:6)
Nretail.create(network_id:6, model_id:14, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:6, model_id:15, month_id:4, year_id:7, number:0, target:3)
Nretail.create(network_id:7, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:2, month_id:4, year_id:7, number:2, target:3)
Nretail.create(network_id:7, model_id:3, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:6, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:7, model_id:7, month_id:4, year_id:7, number:3, target:4)
Nretail.create(network_id:7, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:9, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:7, model_id:10, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:7, model_id:13, month_id:4, year_id:7, number:4, target:8)
Nretail.create(network_id:7, model_id:14, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:7, model_id:15, month_id:4, year_id:7, number:1, target:4)
Nretail.create(network_id:8, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:2, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:8, model_id:3, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:6, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:8, model_id:7, month_id:4, year_id:7, number:0, target:3)
Nretail.create(network_id:8, model_id:8, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:8, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:10, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:8, model_id:13, month_id:4, year_id:7, number:4, target:5)
Nretail.create(network_id:8, model_id:14, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:8, model_id:15, month_id:4, year_id:7, number:2, target:3)
Nretail.create(network_id:9, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:2, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:9, model_id:3, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:6, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:7, month_id:4, year_id:7, number:5, target:4)
Nretail.create(network_id:9, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:9, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:9, model_id:13, month_id:4, year_id:7, number:2, target:6)
Nretail.create(network_id:9, model_id:14, month_id:4, year_id:7, number:2, target:2)
Nretail.create(network_id:9, model_id:15, month_id:4, year_id:7, number:2, target:4)
Nretail.create(network_id:10, model_id:1, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:10, model_id:2, month_id:4, year_id:7, number:7, target:10)
Nretail.create(network_id:10, model_id:3, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:10, model_id:4, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:10, model_id:5, month_id:4, year_id:7, number:1, target:2)
Nretail.create(network_id:10, model_id:6, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:10, model_id:7, month_id:4, year_id:7, number:8, target:15)
Nretail.create(network_id:10, model_id:8, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:10, model_id:9, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:10, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:10, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:10, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:10, model_id:13, month_id:4, year_id:7, number:10, target:23)
Nretail.create(network_id:10, model_id:14, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:10, model_id:15, month_id:4, year_id:7, number:11, target:10)
Nretail.create(network_id:11, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:11, model_id:2, month_id:4, year_id:7, number:3, target:4)
Nretail.create(network_id:11, model_id:3, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:11, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:11, model_id:5, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:11, model_id:6, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:11, model_id:7, month_id:4, year_id:7, number:10, target:6)
Nretail.create(network_id:11, model_id:8, month_id:4, year_id:7, number:2, target:1)
Nretail.create(network_id:11, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:11, model_id:10, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:11, model_id:11, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:11, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:11, model_id:13, month_id:4, year_id:7, number:7, target:10)
Nretail.create(network_id:11, model_id:14, month_id:4, year_id:7, number:1, target:2)
Nretail.create(network_id:11, model_id:15, month_id:4, year_id:7, number:6, target:6)
Nretail.create(network_id:12, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:2, month_id:4, year_id:7, number:1, target:2)
Nretail.create(network_id:12, model_id:3, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:12, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:5, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:6, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:12, model_id:7, month_id:4, year_id:7, number:5, target:4)
Nretail.create(network_id:12, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:12, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:12, model_id:13, month_id:4, year_id:7, number:1, target:4)
Nretail.create(network_id:12, model_id:14, month_id:4, year_id:7, number:1, target:2)
Nretail.create(network_id:12, model_id:15, month_id:4, year_id:7, number:4, target:2)
Nretail.create(network_id:13, model_id:1, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:13, model_id:2, month_id:4, year_id:7, number:10, target:7)
Nretail.create(network_id:13, model_id:3, month_id:4, year_id:7, number:1, target:2)
Nretail.create(network_id:13, model_id:4, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:13, model_id:5, month_id:4, year_id:7, number:2, target:2)
Nretail.create(network_id:13, model_id:6, month_id:4, year_id:7, number:2, target:4)
Nretail.create(network_id:13, model_id:7, month_id:4, year_id:7, number:16, target:15)
Nretail.create(network_id:13, model_id:8, month_id:4, year_id:7, number:1, target:3)
Nretail.create(network_id:13, model_id:9, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:13, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:13, model_id:11, month_id:4, year_id:7, number:1, target:0)
Nretail.create(network_id:13, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:13, model_id:13, month_id:4, year_id:7, number:4, target:19)
Nretail.create(network_id:13, model_id:14, month_id:4, year_id:7, number:2, target:3)
Nretail.create(network_id:13, model_id:15, month_id:4, year_id:7, number:13, target:10)
Nretail.create(network_id:14, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:14, model_id:2, month_id:4, year_id:7, number:2, target:2)
Nretail.create(network_id:14, model_id:3, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:14, model_id:4, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:14, model_id:5, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:14, model_id:6, month_id:4, year_id:7, number:2, target:1)
Nretail.create(network_id:14, model_id:7, month_id:4, year_id:7, number:4, target:5)
Nretail.create(network_id:14, model_id:8, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:14, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:14, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:14, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:14, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:14, model_id:13, month_id:4, year_id:7, number:6, target:8)
Nretail.create(network_id:14, model_id:14, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:14, model_id:15, month_id:4, year_id:7, number:6, target:3)
Nretail.create(network_id:15, model_id:1, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:15, model_id:2, month_id:4, year_id:7, number:3, target:4)
Nretail.create(network_id:15, model_id:3, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:15, model_id:4, month_id:4, year_id:7, number:1, target:0)
Nretail.create(network_id:15, model_id:5, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:15, model_id:6, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:15, model_id:7, month_id:4, year_id:7, number:4, target:8)
Nretail.create(network_id:15, model_id:8, month_id:4, year_id:7, number:1, target:1)
Nretail.create(network_id:15, model_id:9, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:15, model_id:10, month_id:4, year_id:7, number:0, target:1)
Nretail.create(network_id:15, model_id:11, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:15, model_id:12, month_id:4, year_id:7, number:0, target:0)
Nretail.create(network_id:15, model_id:13, month_id:4, year_id:7, number:4, target:10)
Nretail.create(network_id:15, model_id:14, month_id:4, year_id:7, number:0, target:2)
Nretail.create(network_id:15, model_id:15, month_id:4, year_id:7, number:5, target:6)

#Apr 2014 Network
Nretail.create(network_id:1, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:2, month_id:4, year_id:6, number:2)
Nretail.create(network_id:1, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:7, month_id:4, year_id:6, number:3)
Nretail.create(network_id:1, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:1, model_id:14, month_id:4, year_id:6, number:1)
Nretail.create(network_id:1, model_id:15, month_id:4, year_id:6, number:1)
Nretail.create(network_id:2, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:2, month_id:4, year_id:6, number:3)
Nretail.create(network_id:2, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:4, month_id:4, year_id:6, number:1)
Nretail.create(network_id:2, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:7, month_id:4, year_id:6, number:7)
Nretail.create(network_id:2, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:9, month_id:4, year_id:6, number:1)
Nretail.create(network_id:2, model_id:10, month_id:4, year_id:6, number:1)
Nretail.create(network_id:2, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:2, model_id:14, month_id:4, year_id:6, number:2)
Nretail.create(network_id:2, model_id:15, month_id:4, year_id:6, number:3)
Nretail.create(network_id:3, model_id:1, month_id:4, year_id:6, number:2)
Nretail.create(network_id:3, model_id:2, month_id:4, year_id:6, number:7)
Nretail.create(network_id:3, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:6, month_id:4, year_id:6, number:1)
Nretail.create(network_id:3, model_id:7, month_id:4, year_id:6, number:16)
Nretail.create(network_id:3, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:10, month_id:4, year_id:6, number:3)
Nretail.create(network_id:3, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:3, model_id:14, month_id:4, year_id:6, number:2)
Nretail.create(network_id:3, model_id:15, month_id:4, year_id:6, number:12)
Nretail.create(network_id:4, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:2, month_id:4, year_id:6, number:1)
Nretail.create(network_id:4, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:7, month_id:4, year_id:6, number:3)
Nretail.create(network_id:4, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:4, model_id:14, month_id:4, year_id:6, number:1)
Nretail.create(network_id:4, model_id:15, month_id:4, year_id:6, number:2)
Nretail.create(network_id:5, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:2, month_id:4, year_id:6, number:1)
Nretail.create(network_id:5, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:7, month_id:4, year_id:6, number:2)
Nretail.create(network_id:5, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:5, model_id:14, month_id:4, year_id:6, number:3)
Nretail.create(network_id:5, model_id:15, month_id:4, year_id:6, number:2)
Nretail.create(network_id:6, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:2, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:7, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:14, month_id:4, year_id:6, number:0)
Nretail.create(network_id:6, model_id:15, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:2, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:7, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:14, month_id:4, year_id:6, number:0)
Nretail.create(network_id:7, model_id:15, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:2, month_id:4, year_id:6, number:2)
Nretail.create(network_id:8, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:6, month_id:4, year_id:6, number:2)
Nretail.create(network_id:8, model_id:7, month_id:4, year_id:6, number:2)
Nretail.create(network_id:8, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:8, model_id:14, month_id:4, year_id:6, number:2)
Nretail.create(network_id:8, model_id:15, month_id:4, year_id:6, number:5)
Nretail.create(network_id:9, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:2, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:7, month_id:4, year_id:6, number:3)
Nretail.create(network_id:9, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:14, month_id:4, year_id:6, number:0)
Nretail.create(network_id:9, model_id:15, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:2, month_id:4, year_id:6, number:4)
Nretail.create(network_id:10, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:7, month_id:4, year_id:6, number:26)
Nretail.create(network_id:10, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:10, model_id:14, month_id:4, year_id:6, number:14)
Nretail.create(network_id:10, model_id:15, month_id:4, year_id:6, number:16)
Nretail.create(network_id:11, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:2, month_id:4, year_id:6, number:4)
Nretail.create(network_id:11, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:6, month_id:4, year_id:6, number:2)
Nretail.create(network_id:11, model_id:7, month_id:4, year_id:6, number:14)
Nretail.create(network_id:11, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:9, month_id:4, year_id:6, number:1)
Nretail.create(network_id:11, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:11, model_id:14, month_id:4, year_id:6, number:4)
Nretail.create(network_id:11, model_id:15, month_id:4, year_id:6, number:8)
Nretail.create(network_id:12, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:2, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:7, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:14, month_id:4, year_id:6, number:0)
Nretail.create(network_id:12, model_id:15, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:2, month_id:4, year_id:6, number:5)
Nretail.create(network_id:13, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:6, month_id:4, year_id:6, number:1)
Nretail.create(network_id:13, model_id:7, month_id:4, year_id:6, number:20)
Nretail.create(network_id:13, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:13, model_id:14, month_id:4, year_id:6, number:6)
Nretail.create(network_id:13, model_id:15, month_id:4, year_id:6, number:15)
Nretail.create(network_id:14, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:2, month_id:4, year_id:6, number:3)
Nretail.create(network_id:14, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:7, month_id:4, year_id:6, number:10)
Nretail.create(network_id:14, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:14, model_id:14, month_id:4, year_id:6, number:1)
Nretail.create(network_id:14, model_id:15, month_id:4, year_id:6, number:6)
Nretail.create(network_id:15, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:2, month_id:4, year_id:6, number:2)
Nretail.create(network_id:15, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:7, month_id:4, year_id:6, number:5)
Nretail.create(network_id:15, model_id:8, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:15, model_id:14, month_id:4, year_id:6, number:6)
Nretail.create(network_id:15, model_id:15, month_id:4, year_id:6, number:11)
Nretail.create(network_id:16, model_id:1, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:2, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:3, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:4, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:5, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:6, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:7, month_id:4, year_id:6, number:6)
Nretail.create(network_id:16, model_id:8, month_id:4, year_id:6, number:1)
Nretail.create(network_id:16, model_id:9, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:10, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:11, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:12, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:13, month_id:4, year_id:6, number:0)
Nretail.create(network_id:16, model_id:14, month_id:4, year_id:6, number:1)
Nretail.create(network_id:16, model_id:15, month_id:4, year_id:6, number:2)

#Mar 2014 Network
Nretail.create(network_id:1, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:2, month_id:3, year_id:6, number:1)
Nretail.create(network_id:1, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:7, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:8, month_id:3, year_id:6, number:1)
Nretail.create(network_id:1, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:13, month_id:3, year_id:6, number:1)
Nretail.create(network_id:1, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:1, model_id:15, month_id:3, year_id:6, number:2)
Nretail.create(network_id:2, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:2, month_id:3, year_id:6, number:3)
Nretail.create(network_id:2, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:7, month_id:3, year_id:6, number:12)
Nretail.create(network_id:2, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:2, model_id:13, month_id:3, year_id:6, number:4)
Nretail.create(network_id:2, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:2, model_id:15, month_id:3, year_id:6, number:8)
Nretail.create(network_id:3, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:2, month_id:3, year_id:6, number:1)
Nretail.create(network_id:3, model_id:3, month_id:3, year_id:6, number:1)
Nretail.create(network_id:3, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:5, month_id:3, year_id:6, number:2)
Nretail.create(network_id:3, model_id:6, month_id:3, year_id:6, number:2)
Nretail.create(network_id:3, model_id:7, month_id:3, year_id:6, number:20)
Nretail.create(network_id:3, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:10, month_id:3, year_id:6, number:3)
Nretail.create(network_id:3, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:13, month_id:3, year_id:6, number:9)
Nretail.create(network_id:3, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:3, model_id:15, month_id:3, year_id:6, number:14)
Nretail.create(network_id:4, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:2, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:6, month_id:3, year_id:6, number:1)
Nretail.create(network_id:4, model_id:7, month_id:3, year_id:6, number:7)
Nretail.create(network_id:4, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:4, model_id:13, month_id:3, year_id:6, number:1)
Nretail.create(network_id:4, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:4, model_id:15, month_id:3, year_id:6, number:4)
Nretail.create(network_id:5, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:2, month_id:3, year_id:6, number:3)
Nretail.create(network_id:5, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:5, month_id:3, year_id:6, number:1)
Nretail.create(network_id:5, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:7, month_id:3, year_id:6, number:3)
Nretail.create(network_id:5, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:5, model_id:13, month_id:3, year_id:6, number:5)
Nretail.create(network_id:5, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:5, model_id:15, month_id:3, year_id:6, number:4)
Nretail.create(network_id:6, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:2, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:5, month_id:3, year_id:6, number:1)
Nretail.create(network_id:6, model_id:6, month_id:3, year_id:6, number:1)
Nretail.create(network_id:6, model_id:7, month_id:3, year_id:6, number:3)
Nretail.create(network_id:6, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:6, model_id:13, month_id:3, year_id:6, number:3)
Nretail.create(network_id:6, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:6, model_id:15, month_id:3, year_id:6, number:2)
Nretail.create(network_id:7, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:2, month_id:3, year_id:6, number:1)
Nretail.create(network_id:7, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:7, month_id:3, year_id:6, number:5)
Nretail.create(network_id:7, model_id:8, month_id:3, year_id:6, number:1)
Nretail.create(network_id:7, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:7, model_id:13, month_id:3, year_id:6, number:5)
Nretail.create(network_id:7, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:7, model_id:15, month_id:3, year_id:6, number:5)
Nretail.create(network_id:8, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:2, month_id:3, year_id:6, number:4)
Nretail.create(network_id:8, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:7, month_id:3, year_id:6, number:2)
Nretail.create(network_id:8, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:13, month_id:3, year_id:6, number:1)
Nretail.create(network_id:8, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:8, model_id:15, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:2, month_id:3, year_id:6, number:3)
Nretail.create(network_id:9, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:7, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:13, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:9, model_id:15, month_id:3, year_id:6, number:3)
Nretail.create(network_id:10, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:10, model_id:2, month_id:3, year_id:6, number:7)
Nretail.create(network_id:10, model_id:3, month_id:3, year_id:6, number:1)
Nretail.create(network_id:10, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:10, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:10, model_id:6, month_id:3, year_id:6, number:1)
Nretail.create(network_id:10, model_id:7, month_id:3, year_id:6, number:12)
Nretail.create(network_id:10, model_id:8, month_id:3, year_id:6, number:2)
Nretail.create(network_id:10, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:10, model_id:10, month_id:3, year_id:6, number:1)
Nretail.create(network_id:10, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:10, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:10, model_id:13, month_id:3, year_id:6, number:10)
Nretail.create(network_id:10, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:10, model_id:15, month_id:3, year_id:6, number:11)
Nretail.create(network_id:11, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:2, month_id:3, year_id:6, number:2)
Nretail.create(network_id:11, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:6, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:7, month_id:3, year_id:6, number:4)
Nretail.create(network_id:11, model_id:8, month_id:3, year_id:6, number:1)
Nretail.create(network_id:11, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:10, month_id:3, year_id:6, number:1)
Nretail.create(network_id:11, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:13, month_id:3, year_id:6, number:4)
Nretail.create(network_id:11, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:11, model_id:15, month_id:3, year_id:6, number:5)
Nretail.create(network_id:12, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:2, month_id:3, year_id:6, number:1)
Nretail.create(network_id:12, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:6, month_id:3, year_id:6, number:1)
Nretail.create(network_id:12, model_id:7, month_id:3, year_id:6, number:4)
Nretail.create(network_id:12, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:13, month_id:3, year_id:6, number:2)
Nretail.create(network_id:12, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:12, model_id:15, month_id:3, year_id:6, number:4)
Nretail.create(network_id:13, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:2, month_id:3, year_id:6, number:6)
Nretail.create(network_id:13, model_id:3, month_id:3, year_id:6, number:1)
Nretail.create(network_id:13, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:5, month_id:3, year_id:6, number:4)
Nretail.create(network_id:13, model_id:6, month_id:3, year_id:6, number:4)
Nretail.create(network_id:13, model_id:7, month_id:3, year_id:6, number:17)
Nretail.create(network_id:13, model_id:8, month_id:3, year_id:6, number:1)
Nretail.create(network_id:13, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:13, month_id:3, year_id:6, number:5)
Nretail.create(network_id:13, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:13, model_id:15, month_id:3, year_id:6, number:8)
Nretail.create(network_id:14, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:2, month_id:3, year_id:6, number:7)
Nretail.create(network_id:14, model_id:3, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:5, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:6, month_id:3, year_id:6, number:1)
Nretail.create(network_id:14, model_id:7, month_id:3, year_id:6, number:5)
Nretail.create(network_id:14, model_id:8, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:9, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:13, month_id:3, year_id:6, number:2)
Nretail.create(network_id:14, model_id:14, month_id:3, year_id:6, number:0)
Nretail.create(network_id:14, model_id:15, month_id:3, year_id:6, number:6)
Nretail.create(network_id:15, model_id:1, month_id:3, year_id:6, number:0)
Nretail.create(network_id:15, model_id:2, month_id:3, year_id:6, number:2)
Nretail.create(network_id:15, model_id:3, month_id:3, year_id:6, number:2)
Nretail.create(network_id:15, model_id:4, month_id:3, year_id:6, number:0)
Nretail.create(network_id:15, model_id:5, month_id:3, year_id:6, number:1)
Nretail.create(network_id:15, model_id:6, month_id:3, year_id:6, number:1)
Nretail.create(network_id:15, model_id:7, month_id:3, year_id:6, number:8)
Nretail.create(network_id:15, model_id:8, month_id:3, year_id:6, number:2)
Nretail.create(network_id:15, model_id:9, month_id:3, year_id:6, number:1)
Nretail.create(network_id:15, model_id:10, month_id:3, year_id:6, number:0)
Nretail.create(network_id:15, model_id:11, month_id:3, year_id:6, number:0)
Nretail.create(network_id:15, model_id:12, month_id:3, year_id:6, number:0)
Nretail.create(network_id:15, model_id:13, month_id:3, year_id:6, number:2)
Nretail.create(network_id:15, model_id:14, month_id:3, year_id:6, number:1)
Nretail.create(network_id:15, model_id:15, month_id:3, year_id:6, number:6)
